### ISSUE TITLE
RK3328 : Improve the bootloader update time

### ISSUE THREAD

**Issue by LongChair** [Kwiboo/linux-rockchip#10]
Currently the bootloader update in LE takes quite a while .. 1-2 minutes.

This is probably due to the size of the files we are updating.
@Kwiboo mentionned that we could maybe trim those files as they are padded with zeros.
To be investigated :)

**Comment by Kwiboo** [comment]
A possible workaround could be to skip idbloader/u-boot/trust update when `/storage/.update/.nobootloader` or similar exits

**Comment by LongChair** [comment]
What would create that .nobootloader ?

Maybe another way could be to have some trust.md5 file that we can compare with current md5 and flash only when they don't match .

This way whatever file that didn't change would be skipped ?

**Comment by LongChair** [comment]
Here is a bootloader update summuary

![bootloader](https://user-images.githubusercontent.com/2814651/27129217-da9045fa-5101-11e7-86d5-bfa2ce6a080f.JPG)

Don't the update rates look very low ? are we writting to sdcard ? 
If so i don't uderstand how we achieve so lower write rates ... @Kwiboo ? :)

**Comment by LongChair** [comment]
Ok so using the patch below to increase the blocksize to `64k`makes it behave a lot better :

```
diff --git a/projects/Rockchip/packages/u-boot/scripts/update.sh b/projects/Rockchip/packages/u-boot/scripts/update.sh
index 123088b..5902fa4 100755
--- a/projects/Rockchip/packages/u-boot/scripts/update.sh
+++ b/projects/Rockchip/packages/u-boot/scripts/update.sh
@@ -50,15 +50,15 @@ fi
 # update bootloader
   if [ -f "$SYSTEM_ROOT/usr/share/bootloader/idbloader.img" ]; then
     echo "*** updating idbloader.img on: $BOOT_DISK ..."
-    dd if=$SYSTEM_ROOT/usr/share/bootloader/idbloader.img of=$BOOT_DISK conv=fsync seek=64
+    dd if=$SYSTEM_ROOT/usr/share/bootloader/idbloader.img of=$BOOT_DISK conv=fsync seek=1 bs=32k
   fi
   if [ -f "$SYSTEM_ROOT/usr/share/bootloader/uboot.img" ]; then
     echo "*** updating uboot.img on: $BOOT_DISK ..."
-    dd if=$SYSTEM_ROOT/usr/share/bootloader/uboot.img of=$BOOT_DISK conv=fsync seek=16384
+    dd if=$SYSTEM_ROOT/usr/share/bootloader/uboot.img of=$BOOT_DISK conv=fsync seek=128 bs=64k
   fi
   if [ -f "$SYSTEM_ROOT/usr/share/bootloader/trust.img" ]; then
     echo "*** updating trust.img on: $BOOT_DISK ..."
-    dd if=$SYSTEM_ROOT/usr/share/bootloader/trust.img of=$BOOT_DISK conv=fsync seek=24576
+    dd if=$SYSTEM_ROOT/usr/share/bootloader/trust.img of=$BOOT_DISK conv=fsync seek=192 bs=64k
   fi

 # mount $BOOT_ROOT r/o
```
Will take now 1 sec for everything in bootloader.

@Kwiboo : can you update the script with that patch and close this issue when it's done ? :)

**Comment by LongChair** [comment]
Done, closing :)
