### ISSUE TITLE
RK3328 : device locks up after a while

### ISSUE THREAD

**Issue by omegamoon** [Kwiboo/linux-rockchip#18]
The rk3328 device currently locks up after a while. sometimes it reboots, and other times it just locks up.

I collected a couple of stack traces while playing media in Kodi which I will add separately. When the device is idle, doing nothing, it also locks up after a while, but then I see no stack trace at all... it just locks up.

Currently it looks as if the device locks up after approximately 15-20mins... always!

[lockup_kernel_traces.tar.gz](https://github.com/Kwiboo/linux-rockchip/files/1097715/lockup_kernel_traces.tar.gz)

**Comment by LongChair** [comment]
with the latest changes I had rock64 to run a lot longer. 
@omegamoon : could you check if you still have that behavior with those ?

**Comment by Kwiboo** [comment]
the ~15-20 min lockup issue have also been resolved on my Z28 with the latest changes, I think we can close this once @omegamoon have confirmed the same

**Comment by yanghanxing** [comment]
The trust.img update should resolve the issue.

**Comment by omegamoon** [comment]
no lockups seen after applying last changes.
closing this issue

**Comment by suppenkasper0815** [comment]
@omegamoon Could you please send me some hints for Alfawise Z28 Pro (RK3228) and RK3229-Images per PM?
