### ISSUE TITLE
RK3328 : macphy support is missing

### ISSUE THREAD

**Issue by LongChair** [Kwiboo/linux-rockchip#2]
Kernel as support for the externel GMACPHY but not internal MACPHY

**Comment by Kwiboo** [comment]
We made some initial testing with https://github.com/Kwiboo/linux-rockchip/commit/7b7e611421968c62ae84765ac51c642b1a5ab281 but we must have missed something, probably some clock and/or special phy configuration?

**Comment by SuperDavidWu** [comment]
I did three patches for the internal phy, which made internal MACPHY worked on my rk3328-evb board.

[0001-net-phy-Add-rockchip-phy-support.txt](https://github.com/Kwiboo/linux-rockchip/files/1080826/0001-net-phy-Add-rockchip-phy-support.txt)
[0002-ethernet-stmmac-dwmac-rk-Add-support-internal-phy-fo.txt](https://github.com/Kwiboo/linux-rockchip/files/1080828/0002-ethernet-stmmac-dwmac-rk-Add-support-internal-phy-fo.txt)
[0003-arm64-dts-rockchip-Add-support-gmac2phy-for-rk3328.txt](https://github.com/Kwiboo/linux-rockchip/files/1080827/0003-arm64-dts-rockchip-Add-support-gmac2phy-for-rk3328.txt)

**Comment by LongChair** [comment]
Confirmed working by @kwiboo :)

**Comment by yanghanxing** [comment]
We will merge to release-4.4 branch after the code upstream completed.

**Comment by SuperDavidWu** [comment]
Hi

Did you have any UI displayed issue, if you apply this patches for internal phy?

**Comment by LongChair** [comment]
what kind of UI issues are you talking about ?

**Comment by SuperDavidWu** [comment]
Nothing is displayed on the monitor.

**Comment by LongChair** [comment]
no i'm using macphy since a few days, i didn't see any display issues

**Comment by SuperDavidWu** [comment]
Okay, that‘s all right, thanks！

**Comment by LongChair** [comment]
@SuperDavidWu : we were a few commits back compared to GH, i just updated from `13dbe2cc` to `1763310` and now i have a black screen when i boot up.

**Comment by yanghanxing** [comment]
I haven't encounter the issue after merge MACPHY patches in lastest kernel code.
@LongChair  please check again for it.

**Comment by LongChair** [comment]
Closing this as it's been merged.
