### ISSUE TITLE
RK3328 : MPP MPEG2 decoder doesn't seem to work.

### ISSUE THREAD

**Issue by LongChair** [Kwiboo/linux-rockchip#26]
We have used successfully `H264` / `H265` / `MPEG4` / `VP8` / `VP9` with MPP, but it seems that `MPEG2` decoding is having some issues.

We are getting error messages during the decoding :
```
mpp_device: mpp_device_wait_reg ioctl VPU_IOC_GET_REG failed ret -1 errno 110 Connection timed out
hal_m2vd_reg: mpp_device_wait_reg return error:110
m2vd_parser: [m2v]: (ref_frame_cnt[1] < 2) && (frame_cur->picCodingType[3] == B_TYPE)
```

I tested it with several MPEG2 files and always have the same result.

@wzyy2 gave a try to it with gstreamer as well and seems to have found similar issue.
The tested sample file below is known to be working as a test sample for Kodi.

You can find it here :
https://drive.google.com/file/d/0BwxFVkl63-lETXlOa3hEMmVyZGM/view?usp=sharing
(http://kodi.wiki/view/Samples , section 3, File #12)

@yanghanxing : if you could have this checked it would be nice, MPEG2 is interesting for Live TV playback.

**Comment by smp79** [comment]
Does VC-1 decoding work?
