### ISSUE TITLE
Can't find the IP address of Rock64

### ISSUE THREAD

**Issue by FutureTense** [Kwiboo/linux-rockchip#27]
I want to SSH into the SBC, but I can't find the IP address in my router's client list.  The system info gets an ip of 168.254.1.14

It appears the ethernet is not getting a connection.  Any ideas?

**Comment by Kwiboo** [comment]
No idea, I would recommend using a serial console to see what is going on.

Please use the ROCK64 forum for more help and support: https://forum.pine64.org/forumdisplay.php?fid=85
