### ISSUE TITLE
rk3399 libhybris and Android gralloc Mali driver

### ISSUE THREAD

**Issue by ovidiu31** [Kwiboo/linux-rockchip#30]
Hello @Kwiboo 

Would be possible to add support in your build environment for ARM Mali-T860 MP4 GPU from the rk3399 SoC?
I have working kernel 4.4.55 #474 SMP Tue Sep 5 09:09:33 CST 2017 aarch64 GNU/Linux bootloader and almost all the stuff compiling and running fine with your builds except the GPU/VPU acceleration.
Thank you for reading and considering.

**Comment by Kwiboo** [comment]
Hello @ovidiu31, I only have rk3288 (ASUS Tinker Board) and rk3328 (ROCK64, Z28 and soon RockBox) devices so I cannot test or verify if anything works on rk3399 or not.

The `mali-rockchip` package should already support installing Mali-T860 user-space drivers (untested).
I think that if you create a new `projects/Rockchip/devices/$DEVICE` folder, changes `$DEVICE/options` to use `MALI_FAMILY="t860"` and uses a custom `$DEVICE/linux/linux.aarch64.conf` tailored for your device/rk3399 it should be possible.

**Comment by ovidiu31** [comment]
@Kwiboo  thanks a lot for help and assist.
if you want i can send you an development board with rk3399

**Comment by ovidiu31** [comment]
@Kwiboo 
failed to compile for rk3399 with the modifications you suggested

make[4]: Entering directory '/root/LibreELEC.tv/build.LibreELEC-RK3399.aarch64-8.2-devel/openssl-1.0.2l/.x86_64-linux-gnu/engines/ccgost'
../../libcrypto.so: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
