### ISSUE TITLE
RK3328 : Copy Lock ups

### ISSUE THREAD

**Issue by LongChair** [Kwiboo/linux-rockchip#6]
It seems that when copying from USB to SdCard and from ethernet to sdcard some lockups happen.

I have reproduced that copying from network to Sdcard on files that are over 1 gigbyte. device will hang up on a spinlock. will try to get a kernel log if possible.

**Comment by Kwiboo** [comment]
Not packing bl32 into trust.img seems to have solved this USB copy issue.
